name: Create container, push and deploy

on:
  release:
    types: [published]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip deploy')" # will not run if the commit contains that phrase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Docker Meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/towech-financeApp/CateogryReportService
        tag-sha: true
        tag-edge: false
        tag-latest: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        target: 'prod'
        file: ./Dockerfile
        build-args: |
          REACT_APP_WEBAPI=${{ secrets.API_URL }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: deployment
        run: |
          docker rm -f catRepService 2> /dev/null || true
          docker image rm ghcr.io/towech-financeapp/cateogryreportservice 2> /dev/null || true
          docker pull ghcr.io/towech-financeapp/cateogryreportservice:latest
          docker run -d \
          --restart unless-stopped \
          --name catRepService \
          --network towech-finance-network \
          -v /srv/logs/CategoryReportService:/usr/app/logs \
          --env-file /srv/environments/CategoryReportService.env \
          ghcr.io/towech-financeapp/cateogryreportservice:latest
          docker image prune -f